service: aws-kotlin-jvm-maven
provider:
  name: aws
  runtime: java8
  region: eu-central-1
package:
  artifact: target/hello-dev.jar
functions:
  hello:
    handler: com.serverless.Handler
    events:
      - http:
          path: hello
          method: get